#!/usr/bin/env python3
"""Apply Serbian Latin fixes to driving manual MD; never touch image URL segments."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MD = ROOT / "docs" / "Ispit Voznje Za Desetku.md"
IMG = re.compile(r"(\!\[\]\([^)]+\))")


def outside_img(text: str, old: str, new: str) -> str:
    parts = IMG.split(text)
    for i in range(0, len(parts), 2):
        parts[i] = parts[i].replace(old, new)
    return "".join(parts)


# Order: longer phrases first, then shorter (morphological)
REPL: list[tuple[str, str]] = [
    ("ukljucujući", "uključujući"),
    ("Pri ukljucivanju", "Pri uključivanju"),
    ("ukljucivanja", "uključivanja"),
    ("ukljucivanje", "uključivanje"),
    ("Ukljucivanje", "Uključivanje"),
    ("UKLJUCIVANJE", "UKLJUČIVANJE"),
    ("ukljucite", "uključite"),
    ("ukljucen", "uključen"),
    ("ukljucena", "uključena"),
    ("ukljuceno", "uključeno"),
    ("ukljuci", "uključi"),
    ("iskljuci", "isključi"),
    ("iskljucenja", "isključenja"),
    ("iskljucivanja", "isključivanja"),
    ("iskljuciti", "isključiti"),
    ("isključivanje", "isključivanje"),
    ("saobraaja", "saobraćaja"),
    ("saobra-caja", "saobraćaja"),
    ("sao bracaj", "saobraćaj"),
    ("saobracainim", "saobraćajnim"),
    ("saobraja", "saobraćaja"),
    ("motormi", "motorni"),
    ("nascin", "način"),
    ("zutog", "žutog"),
    ("zuto", "žuto"),
    ("Zuto", "Žuto"),
    ("ZUT", "ŽUT"),
    ("zutom", "žutom"),
    ("zutim", "žutim"),
    ("ziljeni", "žiljeni"),
    ("provaliya", "provala"),
    ("saobracaj vozila", "saobraćaj vozila"),
    ("vozae ", "vozač "),
    ("vocac ", "vozač "),
    (" vozae", " vozač"),
    ("vozae.", "vozač."),
    ("vozae,", "vozač,"),
    ("vozae:", "vozač:"),
    ("vozae;", "vozač;"),
    (" morala da se uveri", " mora da se uveri"),
    ("prvaca", "pravca"),
    ("odrucivanjem rule", "okretanjem točka upravljača"),
    (" prvcu ", " pravcu "),
    ("pokazivacem", "pokazivačem"),
    (" pokazivac ", " pokazivač "),
    ("gravca", "pravca"),
    ("pokazivaca", "pokazivača"),
    ("bezbe dan ", "bezbedan "),
    ("bryine", "brzine"),
    ("brinu ", "brzinu "),
    (" smalj", " smanj"),
    (" okretanjcm ", " okretanjem "),
    ("mozes ", "možeš "),
    ("Možes ", "Možeš "),
    ("mozete ", "možete "),
    (" Mozete ", " Možete "),
    (" moze ", " može "),
    (" Moze ", " Može "),
    (" ne moze ", " ne može "),
    (" da moze ", " da može "),
    (" moze.", " može."),
    (" moze,", " može,"),
    (" moze:", " može:"),
    (" moze;", " može;"),
    ("moze biti", "može biti"),
    ("moze se ", "može se "),
    (" vrsi ", " vrši "),
    (" vrsi.", " vrši."),
    (" vrsi,", " vrši,"),
    (" vršiti", " vršiti"),
    ("povrsinu", "površinu"),
    ("povrsine", "površine"),
    ("povrsina", "površina"),
    ("povrsini", "površini"),
    ("povrsinom", "površinom"),
    (" POVRS", " POVRŠ"),
    ("opsteg", "opšteg"),
    ("opstem", "opštem"),
    ("opstina", "opština"),
    ("opstine", "opštine"),
    ("opstini", "opštini"),
    ("sluzi ", "služi "),
    (" sluzi.", " služi."),
    ("sluzi da", "služi da"),
    (" nacin ", " način "),
    (" nacin.", " način."),
    (" nacin,", " način,"),
    ("nacina", "načina"),
    ("nacine", "načine"),
    ("nacinu", "načinu"),
    ("duzan ", "dužan "),
    (" duzan", " dužan"),
    ("vaznosti", "važnosti"),
    ("znacajnim", "značajnim"),
    (" znacaj", " značaj"),
    ("uociti", "uočiti"),
    ("uocila", "uočila"),
    ("uocljivi", "uočljivi"),
    ("karakteristicne", "karakteristične"),
    ("strucnim", "stručnim"),
    ("strucnoj", "stručnoj"),
    ("strucno", "stručno"),
    ("skolovanju", "školovanju"),
    ("skolski", "školski"),
    ("kreativnoscu", "kreativnošću"),
    ("umetnickim", "umetničkim"),
    ("obelezje", "obeležje"),
    ("obelezen", "obeležen"),
    ("obelezena", "obeležena"),
    ("obelezeni", "obeleženi"),
    ("obelezavaju", "obeležavaju"),
    ("obelezavanje", "obeležavanje"),
    ("obeleziti", "obeležiti"),
    ("preporucuje", "preporučuje"),
    ("polozila", "položila"),
    ("polozili", "položili"),
    ("prirucnik", "priručnik"),
    ("pri-rucnik", "priručnik"),
    (" ko neposrednog", " kao neposrednog"),
    (" kategorije,proizasao", " kategorije, proizasao"),
    ("uspesnog", "uspešnog"),
    ("obuhvacena", "obuhvaćena"),
    (" cini ", " čini "),
    ("specificnostima", "specifičnostima"),
    ("regularisanih", "regulisanih"),
    ("signalizacji ", "signalizaciji "),
    (" clanova", " članova"),
    (" pri cemu", " pri čemu"),
    (" velkim", " velikim"),
    (" adekvatim", " adekvatnim"),
    ("posma-tranih", "posmatranih"),
    ("dugogodisnjeg", "dugogodišnjeg"),
    ("buducih", "budućih"),
    ("misljenje", "mišljenje"),
    ("razume-vanja", "razumevanja"),
    ("tumacenja", "tumačenja"),
    ("tumacenje", "tumačenje"),
    ("sub-jekata", "subjekata"),
    (" vrsi saobraćaj", " vrši saobraćaj"),
    ("nekategorsani", "nekategorisani"),
    ("oznacen", "označen"),
    ("oznacavaju", "označavaju"),
    ("oznacava", "označava"),
    ("oznacene", "označene"),
    ("uzduzmi", "uzdužni"),
    (" uzduzni", " uzdužni"),
    ("protocnost", "protočnost"),
    (" ciji ", " čiji "),
    (" znace", " znače"),
    (" vecem ", " većem "),
    (" izgradenog", " izgrađenog "),
    (" izgraden ", " izgrađen "),
    (" cije ", " čije "),
    (" medj", " međ"),
    (" izmedu ", " između "),
    ("medusobno", "međusobno"),
    ("slucajevima", "slučajevima"),
    ("slucaju", "slučaju"),
    (" kisa", " kiša"),
    ("sacinjavaju", "sačinjavaju"),
    (" blize ", " bliže "),
    ("objasnjavaju", "objašnjavaju"),
    ("pridrzavati", "pridržavati"),
    (" vaze ", " važe "),
    (" vaze.", " važe."),
    ("zutom", "žutom"),
    (" velicini", " veličini"),
    ("povecanu", "povećanu"),
    ("naznacenu", "naznačenu"),
    (" vecih ", " većih "),
    (" ocito ", " očito "),
    (" obracaju ", " obraćaju "),
    ("paznju", "pažnju"),
    ("decija", "dečija"),
    ("decije", "dečije"),
    ("vecu", "veću"),
    ("vecom", "većom"),
    ("smeru,s ", "smeru, s "),
    ("putu,mestu", "putu, mestu"),
    ("izricitih", "izričitih"),
    ("Odredenim", "Određenim"),
    ("odredenim", "određenim"),
    (" Omogucava", " Omogućava"),
    ("omogucava", "omogućava"),
    (" objasnjenjem", " objašnjenjem"),
    (" duzinu ", " dužinu "),
    (" duzini", " dužini"),
    ("svetlece", "svetleće"),
    ("upa-ljeno", "upaljeno"),
    ("prilagoditi brinu", "prilagoditi brzinu"),
    ("postav-ljenim", "postavljenim"),
    (" zaustav-liania", " zaustavljanja"),
    (" vozae duzan", " vozač dužan"),
    (" zaus-tavljanja", " zaustavljanja"),
    ("reek", "reč"),
    ("ree\"", "reč \""),
    (" narednuje", " naređuje"),  # typo cluster
    ("sman-jenje", "smanjenje"),
    (" zu regulisanje", " za regulisanje"),
    (" saobra-caja", " saobraćaja"),
    (" uésnici", " učesnici"),
    (" postovati", " poštovati"),
    ("Znakovi izricitih", "Znakovi izričitih"),
    ("puttu ", "putu "),
    ("visc ", "više "),
    (" saobra-caj ", " saobraćaj "),
    (" saobra-cajna", " saobraćajna"),
    (" taku.", " traku."),
    (" taku ", " traku "),
    ("Imamo slucaj", "Postoji slučaj"),
    (" obila-Zenje", " obilaženje"),
    (" saobraaja", "saobraćaja"),
    ("jav-nog", "javnog"),
    (" njje ", " nije "),
    (" prven-stva", " prvenstva"),
    (" prven-stveno", " prvenstveno"),
    (" motoma ", " motorna "),
    (" ocekuje", " očekuje"),
    (" trazi ", " traži "),
    ("greske", "greške"),
    ("ciniti", "činiti"),
    ("greskom", "greškom"),
    ("ucensika", "učesnika"),
    ("uesni-ci", "učesnici"),
    (" pro laz", " prolaz"),
    (" reg-ulisanja", " regulisanja"),
    (" ulazeci", " ulazeći"),
    (" reagujie", " reagujte"),
    (" tacke", " tačke"),
    (" cete ", " ćete "),
    ("predividati", "predviđati"),
    ("predividaj", "predviđaj"),
    (" spreciti", " sprečiti"),
    ("Vaseg", "Vašeg"),
    ("Predvidajte", "Predvidite"),
    (" sledeceg", " sledećeg"),
    (" trentukka", " trenutka"),
    (" iznenadenjia", " iznenađenja"),
    (" praenjem", " praćenjem"),
    ("ponasanje", "ponašanje"),
    (" prova ", " prava "),
    (" prova.", " prava."),
    (" tako cete", " tako ćete"),
    ("zakociti", "zakoči"),
    ("Uoiti", "Uočiti"),
    ("Preddvidajte", "Predvidite"),
    (" dozwoljeno", " dozvoljeno"),
    (" prikljucka", " priključka"),
    (" ukljucenje", " uključenje"),
    (" ukljici", " uključi"),
    (" motormi ", " motorni "),
    ("istovermeno", "istovremeno"),
    (" ulienim", " uličnim"),
    (" osvctljem", " osvetljenjem"),
    (" potrebnnu", " potrebnu"),
    (" izvodnje ", " izvođenje "),
    (" postuju", " poštuju"),
    (" pro laza", " prolaza"),
    (" nacin re-", " način re"),
    ("zaustav-lianja", "zaustavljanja"),
    (" duze ", " duže "),
    (" duze,", " duže,"),
    (" cine ", " čine "),
    (" nasa ", " naša "),
    (" nase ", " naše "),
    (" mozemo ", " možemo "),
    (" ukljuceno", " uključeno"),
    ("obelezna", "obeležena"),
    ("Sirinom", "širinom"),
    (" kakao ", " kako "),
    ("granicnici", "graničnici"),
    ("bicik listincke", "biciklističke"),
    ("Zutom", "Žutom"),
    (" tecnosti", " tečnosti"),
    (" kociti", " kočiti"),
    (" kocen", " kočen"),
    (" prikociti", " prikočiti"),
    (" UKLJUCENO", " UKLJUČENO"),
]


def main() -> None:
    t = MD.read_text(encoding="utf-8")
    for old, new in REPL:
        t = outside_img(t, old, new)
    # Fix UČESNIK relative pronoun
    t = outside_img(t, "ili na vozilu, koja tera, vodi", "ili na vozilu, koje vuče, vodi")
    MD.write_text(t, encoding="utf-8")
    print("done", MD)


if __name__ == "__main__":
    main()
