#!/usr/bin/env python3
"""Normalize OCR'd driving manual markdown: Serbian Latin diacritics and common typos.
   Skips replacement inside ![](...) image URLs to preserve file paths."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MD = ROOT / "docs" / "Ispit Voznje Za Desetku.md"

IMG_SPLIT = re.compile(r"(\!\[\]\([^)]+\))")


def replace_outside_images(text: str, old: str, new: str) -> str:
    parts = IMG_SPLIT.split(text)
    for i in range(0, len(parts), 2):
        parts[i] = parts[i].replace(old, new)
    return "".join(parts)


# Longest-first morphological and phrase replacements
REPLACEMENTS: list[tuple[str, str]] = [
    # Mojibake / mixed scripts
    ("uě", "uč"),
    ("učsnike", "učesnike"),
    ("slucajevima", "slučajevima"),
    ("uées", "učes"),
    ("Zvuěni", "Zvučni"),
    # saobraćaj family (longest first)
    ("saobracajnih", "saobraćajnih"),
    ("saobracajnim", "saobraćajnim"),
    ("saobracajnog", "saobraćajnog"),
    ("saobracajnom", "saobraćajnom"),
    ("saobracajno", "saobraćajno"),
    ("saobracajne", "saobraćajne"),
    ("saobracajna", "saobraćajna"),
    ("saobracajnu", "saobraćajnu"),
    ("saobracajni", "saobraćajni"),
    ("saobracajnju", "saobraćajnu"),
    ("saobracajem", "saobraćajem"),
    ("saobracaju", "saobraćaju"),
    ("saobracaja", "saobraćaja"),
    ("SAOBRACAJU", "SAOBRAĆAJU"),
    ("SAOBRACAJA", "SAOBRAĆAJA"),
    ("SAOBRACAJEM", "SAOBRAĆAJEM"),
    ("SAOBRACAJNI", "SAOBRAĆAJNI"),
    ("SAOBRACAJNA", "SAOBRAĆAJNA"),
    ("SAOBRACAJNE", "SAOBRAĆAJNE"),
    ("SAOBRACAJNO", "SAOBRAĆAJNO"),
    ("SAOBRACAJNOM", "SAOBRAĆAJNOM"),
    ("SAOBRACAJNOG", "SAOBRAĆAJNOG"),
    ("SAOBRACAJNIM", "SAOBRAĆAJNIM"),
    ("SAOBRACAJNIH", "SAOBRAĆAJNIH"),
    ("saobracaj", "saobraćaj"),
    ("Saobracaj", "Saobraćaj"),
    ("SAOBRACAJ", "SAOBRAĆAJ"),
    ("saobracja", "saobraćaja"),
    ("saobraćaji", "saobraćaj"),  # fix double
    # železnica
    ("ZELEZNICKE", "ŽELEZNIČKE"),
    ("zeleznicke", "železničke"),
    ("zeleznicku", "železničku"),
    ("zeleznickoj", "železničkoj"),
    ("zeleznickog", "železničkog"),
    ("zeleznickim", "železničkim"),
    ("zeleznicka", "železnička"),
    ("zeleznicki", "železnički"),
    ("Zeleznick", "Železničk"),
    ("zeleznice", "železnice"),
    ("zeleznica", "železnica"),
    ("ZELEZNICE", "ŽELEZNICE"),
    ("ZELEZNICA", "ŽELEZNICA"),
    ("Zeleznice", "Železnice"),
    ("Zeleznica", "Železnica"),
    # učesnik
    ("ucesnicima", "učesnicima"),
    ("UCESNICIMA", "UČESNICIMA"),
    ("ucesnika", "učesnika"),
    ("ucesnici", "učesnici"),
    ("ucesniku", "učesniku"),
    ("ucesnika", "učesnika"),
    ("UCESNICI", "UČESNICI"),
    ("UCESNIKA", "UČESNIKA"),
    ("UCESNIKU", "UČESNIKU"),
    ("ucesnik", "učesnik"),
    ("UCESNIK", "UČESNIK"),
    ("ucestvovalo", "učestvovalo"),
    ("ucestvuju", "učestvuju"),
    ("ucestvuje", "učestvuje"),
    ("ucestvuje", "učestvuje"),
    ("ucestvuje", "učestvuje"),
    ("ucestvuje", "učestvuje"),
    ("ucestvovanje", "učestvovanje"),
    ("ucestvovanja", "učestvovanja"),
    ("ucescem", "učešćem"),
    ("ucesca", "učešća"),
    ("ucesce", "učešće"),
    ("ucesee", "učešće"),
    ("UCESCE", "UČEŠĆE"),
    # vozač
    ("vozaca", "vozača"),
    ("vozaci", "vozači"),
    ("vozacu", "vozaču"),
    ("vozac", "vozač"),
    ("Vozaca", "Vozača"),
    ("Vozaci", "Vozači"),
    ("Vozacu", "Vozaču"),
    ("Vozac", "Vozač"),
    ("VOZACA", "VOZAČA"),
    ("VOZACI", "VOZAČI"),
    ("VOZACU", "VOZAČU"),
    ("VOZAC", "VOZAČ"),
    ("vozaa", "vozača"),
    ("vocaca", "vozača"),
    ("Vozae", "Vozač"),
    ("vozacki", "vozački"),
    ("vozackog", "vozačkog"),
    ("vozacke", "vozačke"),
    # šine
    ("Sinama", "šinama"),
    ("sinama", "šinama"),
    # Common words
    ("zivotinj", "životinj"),
    ("Zivotinj", "Životinj"),
    ("zivotinju", "životinju"),
    ("jase", "jaše"),
    ("krece", "kreće"),
    ("krecu", "kreću"),
    ("kretanja", "kretanja"),
    ("kre tanja", "kretanja"),
    ("prclazi", "prelazi"),
    (" je oot ", " je isključivo "),
    (" cija ", " čija "),
    (" tocka", " točka"),
    (" tocka,", " točka,"),
    ("mreZu", "mrežu"),
    ("mreze", "mreže"),
    ("Sirina", "širina"),
    ("sirina", "širina"),
    ("nesmetan", "nesmetan"),
    ("zaus tavljanje", "zaustavljanje"),
    ("zaus tavljenog", "zaustavljenog"),
    ("zaus tavljen", "zaustavljen"),
    ("iskljucii", "isključiti"),
    ("odgovarajucu", "odgovarajuću"),
    ("odgovarajucem", "odgovarajućem"),
    ("odgovarajuceg", "odgovarajućeg"),
    ("odgovarajucceg", "odgovarajućeg"),
    ("odgovarajuci", "odgovarajući"),
    ("odredenim", "određenim"),
    ("odredenih", "određenih"),
    ("odredena", "određena"),
    ("odredene", "određene"),
    ("odredeno", "određeno"),
    ("odreden", "određen"),
    ("odgovarajucem", "odgovarajućem"),
    ("vueu", "vuču"),
    ("vucu", "vuču"),
    ("vuce", "vuče"),
    ("Vuce", "Vuče"),
    ("strari", "stvari"),
    ("svari", "stvari"),
    ("elektricnom", "električnom"),
    ("elektrieni", "električni"),
    ("vise", "više"),
    ("Vise", "Više"),
    ("VISE", "VIŠE"),
    ("decje", "dečje"),
    ("nemocna", "nemoćna"),
    ("rucna", "ručna"),
    ("covecjeg", "čovečijeg"),
    ("brinom", "brzinom"),
    ("prekinida", "prekida"),
    ("prekinda", "prekida"),
    ("previailu", "pravilu"),
    ("regulise", "reguliše"),
    ("Regulise", "Reguliše"),
    ("prolazenje", "prolaženje"),
    ("prolazenje", "prolaženje"),
    ("kojm", "kojom"),
    ("pos-tupanja", "postupanja"),
    ("provac", "pravac"),
    ("brinzu", "brzinu"),
    ("ograničenja", "ograničenja"),
    ("ogranicenja", "ograničenja"),
    ("ogranicenje", "ograničenje"),
    ("obavestenja", "obaveštenja"),
    ("obavestenje", "obaveštenje"),
    ("obavetenja", "obaveštenja"),
    ("obavetenja", "obaveštenja"),
    ("obavestenj", "obaveštenj"),
    ("opas nosti", "opasnosti"),
    ("uda-ljenosti", "udaljenosti"),
    ("jasnoca", "jasnoća"),
    ("shvvtila", "shvatila"),
    ("provoremeno", "pravovremeno"),
    ("jednstavna", "jednostavna"),
    ("znacenje", "značenje"),
    ("znacenja", "značenja"),
    ("Značenje", "Značenje"),
    ("zmak", "znak"),
    ("stati znakovi", "stari znakovi"),
    ("informisu", "informišu"),
    ("mogucu", "moguću"),
    ("moguce", "moguće"),
    ("moguci", "mogući"),
    ("mogucnost", "mogućnost"),
    ("piriodi", "prirodi"),
    ("kretania", "kretanja"),
    ("reposredno", "neposredno"),
    ("blogovremeno", "blagovremeno"),
    ("najmanjc", "najmanje"),
    ("tricklu", "triciklu"),
    ("naivise", "najviše"),
    ("Vozilla", "vozila"),
    (" piti ", " biti "),
    ("Zivorad", "Živorad"),
    ("Ficovic", "Fićović"),
    ("psihoaktivinih", "psihoaktivnih"),
    ("utoku", "u toku"),
    ("najmaje", "najmanje"),
    ("Resenje", "Rešenje"),
    ("resenje", "rešenje"),
    ("tehnicki", "tehnički"),
    ("Tehnicki", "Tehnički"),
    ("tehničkički", "tehnički"),
    ("tehmicki", "tehnički"),
    ("telhnikom", "tehničkom"),
    ("prucniku", "priručniku"),
    ("prirunika", "priručnika"),
    ("prirunik", "priručnik"),
    ("Prirucnik", "Priručnik"),
    ("prihvaltljivim", "prihvatljivim"),
    ("specifienost", "specifičnost"),
    ("savermen", "savremen"),
    ("kategorize", "kategorije"),
    ("instituticija", "institucija"),
    ("prawne", "pravne"),
    ("navendenje", "navođenje"),
    ("terminologijiom", "terminologijom"),
    ("saobracajinim", "saobraćajnim"),
    ("ijzraza", "i izraza"),
    ("udzbenika", "udžbenika"),
    ("sao-bracajnog", "saobraćajnog"),
    ("defanzivne", "defanzivne"),
    ("DEFANZIVNE", "DEFANZIVNE"),
    ("znaenja", "značenja"),
    ("znaenje", "značenje"),
    ("ill ", "ili "),
    ("vaZnija", "važnija"),
    ("podruc ja", "područja"),
    ("znacaja", "značaja"),
    ("znacajan", "značajan"),
    ("znacajna", "značajna"),
    ("znacajno", "značajno"),
    ("sa-obracaj", "saobraćaj"),
    ("stranne", "strane"),
    ("mesa", "mesta"),
    ("naxin", "način"),
    ("privrremeno", "privremeno"),
    ("ulaze ii", "ulaze i"),
    ("TROTOAR jc", "TROTOAR je"),
    ("obeelezen", "obeležen"),
    ("znakomi", "znakom i"),
    ("proizvodaca", "proizvođača"),
    ("ogranicenja", "ograničenja"),
    ("najvecu", "najveću"),
    ("najveca", "najveća"),
    ("najvece", "najveće"),
    ("najveci", "najveći"),
    ("najvec", "najveć"),
    ("viseg", "višeg"),
    ("tuneli ma", "tunelima"),
    ("tezim", "težim"),
    ("Stetu", "štetu"),
    ("Steta", "šteta"),
    ("Putma", "Putna"),
    ("njhovim", "njihovim"),
    ("jednoobrazna", "jednoobrazna"),
    ("uni-verzalna", "univerzalna"),
    ("sigumosna", "sigurnosna"),
    ("Lonear", "Lončar"),
    ("utvrdvanje", "utvrđivanje"),
    ("tumaenje", "tumačenje"),
    ("vebe", "vežbe"),
    ("izgradujte", "izgrađujte"),
    ("stexenim", "stečenim"),
    ("Cinjeni-ca", "Činjenica"),
    ("kodeds", "kodeks"),
    ("saobraaju", "saobraćaju"),
    ("nec", "neće"),
    ("neposrednih", "neposrednih"),
    ("nepovoljnih", "nepovoljnih"),
    ("obavezama", "obavezama"),
    ("obavestenja", "obaveštenja"),
    ("uskladeni", "uskladjeni"),
    ("usloviljavaju", "uslovljavaju"),
    ("sveobuhvatnjc", "sveobuhvatnije"),
    ("desertku", "desetku"),
    ("lspit", "Ispit"),
    ("Ispit voznje", "Ispit vožnje"),
    ("voznje", "vožnje"),
    ("Voznje", "Vožnje"),
    ("VOZNJE", "VOŽNJE"),
    ("voznjom", "vožnjom"),
    ("voznju", "vožnju"),
    ("voznji", "vožnji"),
    ("voznja", "vožnja"),
    ("Voznja", "Vožnja"),
    ("ABCED", "ABCD"),
    ("dipl.inz.saobracaja", "dipl. inž. saobraćaja"),
    ("dipl.inz.", "dipl. inž."),
    ("dipl ing", "dipl. inž."),
    ("inzenjer", "inženjer"),
    ("Komercijana", "Komercijalna"),
    ("pomoci", "pomoći"),
    ("prve pomoci", "prve pomoći"),
    ("Cacak", "Čačak"),
    ("neovlasceno", "neovlašćeno"),
    ("ovlascen", "ovlašćen"),
    ("ovlascena", "ovlašćena"),
    ("ovlasceno", "ovlašćeno"),
    ("ovlascenih", "ovlašćenih"),
    ("oviascena", "ovlašćena"),
    ("svetiosnih", "svetlosnih"),
    ("zaustavijanje", "zaustavljanje"),
    ("usproravanje", "usporavanje"),
    ("signalizacjia", "signalizacija"),
    ("signalizacjia", "signalizacija"),
    ("Vertikahna", "Vertikalna"),
    ("narednbi", "naredbi"),
    ("zaakovi", "znakovi"),
    ("tramvajia", "tramvaja"),
    ("kolovozai", "kolovozu"),
    ("IKRETANJE", "I KRETANJE"),
    ("SPECIJIALNIH", "SPECIJALNIH"),
    ("DIMENZUE", "DIMENZIJE"),
    ("Tehmicki", "Tehnički"),
    ("Pruzanjem", "Pružanjem"),
    ("pruzanje", "pružanje"),
    ("pruziti", "pružiti"),
    ("pruzi", "pruži"),
    ("srecnu", "srećnu"),
    ("koriscenju", "korišćenju"),
    ("koriscenje", "korišćenje"),
    ("vestine", "veštine"),
    ("opreznost", "opreznost"),
    ("oborena", "oborena"),
    ("kocenja", "kočenja"),
    ("kocenje", "kočenje"),
    ("nepromenjen", "nepromenjen"),
    ("MIMOILAZENJE", "MIMOILAŽENJE"),
    ("mimoilazenje", "mimoilaženje"),
    ("SKRETANJE", "SKRETANJE"),
    ("Polukruzno", "Polukružno"),
    ("polukruzno", "polukružno"),
    ("nepromenjeno", "nepromenjeno"),
    ("zastitnom", "zaštitnom"),
    ("zastitna", "zaštitna"),
]

# Fix accidental double replacements
FIXUPS = [
    ("saobraćajaća", "saobraćaja"),
    ("priručnikučnik", "priručniku"),
    ("Ispit Ispit", "Ispit"),
    ("Ispit vožnje vožnje", "Ispit vožnje"),
    ("u obući ", "u obuci "),
    (" u obući", " u obuci"),
    (" je obući ", " je obuci "),
    ("obući u smislu", "obuci u smislu"),
    ("obući u smishu", "obuci u smislu"),
    ("o obući ", "o obuci "),
    ("uEsnika", "učesnika"),
    ("dipl. inz.", "dipl. inž."),
    ("dipl. inž.saobraćaja", "dipl. inž. saobraćaja"),
    ("zeljeznicom", "železnicom"),
    ("iskljucivo", "isključivo"),
    ("ukljuciti", "uključiti"),
    ("voza ca ", "vozača "),
    ("ZNACENJE", "Značenje"),
    ("znakovi1znaci", "znakovi i znaci"),
]


def strip_page_only_headings(text: str) -> str:
    """Remove ### N headings that are OCR page markers (standalone digit)."""
    return re.sub(r"^###\s+\d+\s*\n", "\n", text, flags=re.MULTILINE)


def apply_normalizations(text: str) -> str:
    """Serbian Latin + OCR typo fixes; never modifies text inside ![](...) segments."""
    for old, new in REPLACEMENTS:
        text = replace_outside_images(text, old, new)
    for old, new in FIXUPS:
        text = replace_outside_images(text, old, new)
    text = strip_page_only_headings(text)
    return text


def main() -> None:
    import sys

    path = Path(sys.argv[1]) if len(sys.argv) > 1 else MD
    text = path.read_text(encoding="utf-8")
    text = apply_normalizations(text)
    path.write_text(text, encoding="utf-8")
    print("Wrote", path)


if __name__ == "__main__":
    main()
